"import { useState, useEffect } from 'react';\nimport { SignedIn, SignedOut, SignInButton, UserButton } from '@clerk/clerk-react';\nimport { collectionsData } from './SignatureCollection/CollectionData';\nimport './Navbar.css';\n\nconst ShoppingBagIcon = ({ className }) => (\n  <svg className={className} fill=\"none\" viewBox=\"0 0 24 24\" strokeWidth=\"1.5\" stroke=\"currentColor\" strokeLinecap=\"round\" strokeLinejoin=\"round\">\n    <path d=\"M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z\" />\n    <line x1=\"3\" y1=\"6\" x2=\"21\" y2=\"6\" />\n    <path d=\"M16 10a4 4 0 0 1-8 0\" />\n  </svg>\n);\n\nexport default function Navbar({ onNavigate, activePage, onSelectCategory, activeCategory }) {\n  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);\n  const [isThemeDark, setIsThemeDark] = useState(false);\n  const [isSearchOpen, setIsSearchOpen] = useState(false);\n  const [searchQuery, setSearchQuery] = useState('');\n  const [isMobileShopOpen, setIsMobileShopOpen] = useState(false);\n  const [isMobileCategoriesOpen, setIsMobileCategoriesOpen] = useState(false);\n  const [isMegaMenuOpen, setIsMegaMenuOpen] = useState(false);\n  const [isScrolled, setIsScrolled] = useState(false);\n  const [cartCount, setCartCount] = useState(0);\n\n  // Sync theme with HTML body attribute\n  useEffect(() => {\n    document.body.setAttribute('data-theme', isThemeDark ? 'dark' : 'light');\n  }, [isThemeDark]);\n\n  // Sync scroll position for sticky/floating styles\n  useEffect(() => {\n    const handleScroll = () => {\n      setIsScrolled(window.scrollY > 20);\n    };\n    window.addEventListener('scroll', handleScroll);\n    return () => {\n      window.removeEventListener('scroll', handleScroll);\n    };\n  }, []);\n\n  // Sync cart count from localStorage\n  useEffect(() => {\n    const syncCart = () => {\n      const count = parseInt(localStorage.getItem('cartCount') || '0');\n      setCartCount(count);\n    };\n    syncCart();\n    window.addEventListener('cart-updated', syncCart);\n    return () => {\n  
<truncated 18994 bytes>
"    <header className={`navbar-wrapper ${activePage === 'home' ? 'on-home' : ''} ${isScrolled ? 'scrolled' : ''}`}>\n\n      {/* Main Navbar */}\n      <nav className=\"navbar\">\n        <div className=\"nav-container\">\n          \n          {/* Left Menu (Shop, Collections, Gifting, Discovery Sets) */}\n          <ul className=\"nav-menu\">\n            <li className=\"nav-item dropdown\">\n              <a href=\"#collection\" className=\"nav-link\" onClick={(e) => handleLinkClick(e, 'shop')}>\n                SHOP <i className=\"fas fa-chevron-down nav-chevron\"></i>\n              </a>\n              <ul className=\"dropdown-menu\">\n                <li><a href=\"#collection\" onClick={(e) => handleCategoryClick(e, 'all')}>Shop All</a></li>\n                <li><a href=\"#collection\" onClick={(e) => handleCategoryClick(e, 'decants')}>Decants</a></li>\n                <li><a href=\"#collection\" onClick={(e) => handleCategoryClick(e, 'fullbottles')}>Full Bottles</a></li>\n                <li className=\"dropdown-divider-item\"></li>\n                <li><a href=\"#collection\" onClick={(e) => handleCategoryClick(e, 'brands')}>Brands</a></li>\n                <li><a href=\"#collection\" onClick={(e) => handleCategoryClick(e, 'families')}>Fragrance Families</a></li>\n                <li><a href=\"#collection\" onClick={(e) => handleCategoryClick(e, 'newarrivals')}>New Arrivals</a></li>\n              </ul>\n            </li>\n\n            <li \n              className=\"nav-item mega-dropdown\"\n              onMouseEnter={() => setIsMegaMenuOpen(true)}\n              onMouseLeave={() => setIsMegaMenuOpen(false)}\n            >\n              <a href=\"#collection\" className=\"nav-link\" onClick={(e) => e.preventDefault()}>\n                COLLECTIONS <i className=\"fas fa-chevron-down nav-chevron\"></i>\n              </a>\n              \n              {/* Collections Mega Menu Panel */}\n              <div className={`mega-menu-panel ${isMegaMenuOpen ? 'open' : ''}`}>\n                <div className=\
<truncated 5012 bytes>
            </li>

            <li className="mobile-nav-item">
              <a href="#gifting" className="mobile-nav-link" onClick={(e) => handleLinkClick(e, 'gifting')}>
                <span>GIFTING</span>
              </a>
            </li>

            <li className="mobile-nav-item">
              <a href="#collection" className="mobile-nav-link" onClick={(e) => handleCategoryClick(e, 'sets')}>
                <span>DISCOVERY SETS</span>
              </a>
"      {/* Main Navbar */}\n      <nav className=\"navbar\">\n        <div className=\"nav-container\">\n          \n          {/* Left Section (Wraps hamburger and desktop menu) */}\n          <div className=\"nav-left-wrapper\">\n            {/* Hamburger Icon for Mobile */}\n            <div className={`hamburger ${isMobileMenuOpen ? 'active' : ''}`} onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}>\n              <span></span>\n              <span></span>\n              <span></span>\n            </div>\n\n            {/* Left Menu (Shop, Collections, Gifting, Discovery Sets) */}\n            <ul className=\"nav-menu\">\n              <li className=\"nav-item dropdown\">\n                <a href=\"#collection\" className=\"nav-link\" onClick={(e) => handleLinkClick(e, 'shop')}>\n                  SHOP <i className=\"fas fa-chevron-down nav-chevron\"></i>\n                </a>\n                <ul className=\"dropdown-menu\">\n                  <li><a href=\"#collection\" onClick={(e) => handleCategoryClick(e, 'all')}>Shop All</a></li>\n                  <li><a href=\"#collection\" onClick={(e) => handleCategoryClick(e, 'decants')}>Decants</a></li>\n                  <li><a href=\"#collection\" onClick={(e) => handleCategoryClick(e, 'fullbottles')}>Full Bottles</a></li>\n                  <li className=\"dropdown-divider-item\"></li>\n                  <li><a href=\"#collection\" onClick={(e) => handleCategoryClick(e, 'brands')}>Brands</a></li>\n                  <li><a href=\"#collection\" onClick={(e) => handleCategoryClick(e, 'families')}>Fragrance Families</a></li>\n                  <li><a href=\"#collection\" onClick={(e) => handleCategoryClick(e, 'newarrivals')}>New Arrivals</a></li>\n                </ul>\n              </li>\n\n              <li \n                className=\"nav-item mega-dropdown\"\n                onMouseEnter={() => setIsMegaMenuOpen(true)}\n                onMouseLeave={() => setIsMegaMenuOpen(false)}\n              >\n                <a href=\"#collection\" className=\"nav-
<truncated 6764 bytes>